### PR TITLE
New node functionality

### PR DESCRIPTION
**Pull request by DanilBaibak**
New node functionality

### CODE REVIEW

**Comment by dmaicher** [comment]
Isn't ```Node::getLayer()``` what you are looking for?

**Comment by dmaicher** [comment]
Ah no sorry not really. So you want to know how many layers are below a node?

**Comment by DanilBaibak** [comment]
Yep. It's a little bit another than Node::getLayer()

Just optimized my code, I recognize that for now I don't need to know the nesting depth :)))
But current functional is working, so you may decided do we need it for future :)

**Comment by dmaicher** [comment]
Closing for now as it has conflicts anyway :yum:

**Pull request closed without merging**
